Challenge2/whatsbusy/subscription/urls.py
from django.urls import include, path
from . import views

# namespace for subscriptions
app_name = "subscription"

urlpatterns = [
    # path to function rendering page to get premium subscription
    path('premium/', views.getPremium,
         name="getPremium"),
    # path to function interacting with STRIPE apis for premium subscription
    path('pay/', views.registerPremium,
         name="registerPremium"),
    # path to function to cancel premium subscription
    path('cancel/', views.cancelPremium,
         name="cancelPremium"),

]

Challenge2/whatsbusy/users/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

# namespace for users
app_name = "users"

urlpatterns = [
    # path to function rendering index page
    path('', views.index, name="index"),
    # path to function rendering Registration page
    path('register/', views.register, name="register"),
    # path to function rendering home page
    path('home/', views.home, name="home"),


]

Challenge2/whatsbusy/whatsbusy/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.contrib.auth.urls import views


urlpatterns = [
    # paths for login and authetication
    path('', include('django.contrib.auth.urls')),
    # paths for home, index and registration  pages
    path('', include('users.urls')),
    # paths for subscription handling
    path('subscription/', include('subscription.urls')),
    # paths for Django admin
    path('admin/', admin.site.urls),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Challenge2/whatsbusy/subscription/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# Subscription model with OnetoOne relationship with the User


class Subscription(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=False)
    trial = models.BooleanField(default=False)
    stripe_customer_id = models.CharField(max_length=500, default='')
    stripe_token_id = models.CharField(max_length=500, default='')
    stripe_subscription_id = models.CharField(max_length=500, default='')

Challenge2/whatsbusy/users/models.py
from django.db import models

# Create your models here.

Challenge2/whatsbusy/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# User registartion form
# Modified and built upon Django default UserCreationForm and User object


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email',
                  'password1', 'password2', )

Challenge2/whatsbusy/subscription/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Subscription
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.conf import settings
from .models import Subscription
from users import views
import stripe


# Create your views here.
stripe.api_key = settings.STRIPE_SECRET_KEY


# Create your views here.

# rendering form to get premium
@login_required
def getPremium(request):
    return render(request, 'checkout.html')

# interecting with STRIPE apis to get premium subscription


@login_required
def registerPremium(request):
    subscription_obj = Subscription.objects.get(user=request.user)
    customer_id = subscription_obj.stripe_customer_id
    card_token = request.POST['stripeToken']
    print("token", card_token)
    # saving card with the customer
    saveCard(subscription_obj, card_token, customer_id)
    print("card saved")
    # generating charge
    charge = chargeCustomer(customer_id)
    print("card charged")
    # Setting up subscription
    subscription_obj = subscribeCustomer(subscription_obj, customer_id)

    subscription_obj.active = True
    trial = subscription_obj.trial
    subscription_obj.save()
    context = {"active": True, "trial": trial}
    return redirect('users:home')


# cancel subscription
@login_required
def cancelPremium(request):
    subscription_obj = Subscription.objects.get(user=request.user)
    subscription_id = subscription_obj.stripe_subscription_id
    stripe_subscription = stripe.Subscription.delete(subscription_id)
    subscription_obj.active = False
    trial = subscription_obj.trial
    subscription_obj.save()
    context = {"active": False, "trial": trial}
    return redirect('users:home')


# link card with customer
def saveCard(subscription, card_token, customer_id):
    if subscription.stripe_token_id == "":
        subscription.stripe_token_id = card_token

        customer = stripe.Customer.modify(
            customer_id,
            source=card_token
        )


# charge customer
def chargeCustomer(customer_id):
    charge = stripe.Charge.create(
        customer=customer_id,
        amount=4999,
        currency='usd'

    )
    return charge


# subscribe a customer
def subscribeCustomer(subscription, customer_id):
    if subscription.active == False and subscription.trial == False:
        stripe_subscription = stripe.Subscription.create(
            customer=customer_id,
            items=[
                {
                    'price': 'price_HIu2PCVQBAlXrB',
                },
            ],
            # trial_end=1589144675,
            trial_period_days=7,
        )
        subscription.stripe_subscription_id = stripe_subscription["id"]
        subscription.trial = True
    else:
        stripe_subscription = stripe.Subscription.create(
            customer=customer_id,
            items=[
                {
                    'price': 'price_HIu2PCVQBAlXrB',
                },
            ],
        )
        subscription.stripe_subscription_id = stripe_subscription["id"]
    return subscription

Challenge2/whatsbusy/users/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from subscription.models import Subscription
# Create your views here.


# main/index page
def index(request):
    if request.user.is_authenticated:
        return render(request, 'home.html')
    else:
        return render(request, 'index.html')


# registeration page
def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login')
        else:
            print("form invalid")
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {'form': form})

# home page
@login_required
def home(request):
    subscription = Subscription.objects.get(user=request.user)
    context = {"active": subscription.active, "trial": subscription.trial}
    return render(request, 'home.html', context)

Challenge2/whatsbusy/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock title%}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    {% block head %} {% endblock head%}
</head>

<body>
    <nav class="navbar navbar-expand bg-primary navbar-dark">



        <!-- Links -->
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'users:home' %}">Whatsbusy</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
        </ul>


        {% else %}
        <a class="navbar-brand" href="{% url 'users:index' %}">Whatsbusy</a>

        {% endif %}

        </ul>
    </nav>
    <div class="content" style="width: 100%; height: 100%;">
        {% block content %}{% endblock content %}
    </div>
</body>

</html>

Challenge2/whatsbusy/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %} Home {%endblock title%}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock head%}
{% block content %}
{% csrf_token %}
<div class="sub-wrapper">
    <div class="sub">
        {% if active%}
        <h3>Premium Subscriber</h3>
        <button type="submit" class="btn btn-primary" onclick="cancel()">CANCEL</button>

        {%else%}
        {% if trial%}
        <h3>Non Premium Subscriber & No trial left!</h3>
        <button type="submit" class="btn btn-primary" onclick="premium()">GET PREMIUM</button>
        {%else%}
        <h3>Non Premium Subscribe & 7 days trial left!</h3>
        <button type="submit" class="btn btn-primary" onclick="premium()">GET PREMIUM</button>

        {% endif %}
        {% endif %}
    </div>
</div>

<script>
    function cancel() {
        location.href = "{% url 'subscription:cancelPremium'%}"
    }

    function premium() {
        location.href = "{% url 'subscription:getPremium'%}"
    }
</script>

{% endblock %}

Challenge2/whatsbusy/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Main {%endblock title%}
{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock head%}
{% block content %}
{% csrf_token %}
<div class="welcome-wrapper">
    <div class="welcome">
        <button type="submit" class="btn btn-primary" onclick=login()>LOGIN</button>
        <button type=" submit" class="btn btn-primary" onclick=register()>REGISTER</button>
    </div>
</div>

<script>
    function login() {
        location.href = " {% url 'login' %}"
    }

    function register() {
        location.href = "{% url 'users:register' %}"
    }

</script>

{% endblock %}

Challenge2/whatsbusy/templates/subscription/checkout.html
{% extends "base.html" %}
{% block title %} Premium {%endblock title%}
{% block head %}

{% load static %}

{% endblock head%}
{% block content %}

<div class="form row">
        <div class="col">
                <div class="row heading-wrapper">
                        <div class="heading">
                                <h3>Premium Subscription is worth $49.99</h3>
                        </div>
                </div>
                <script src="https://js.stripe.com/v3/"></script>
                <div class="row">
                        <div class="col">
                                <form action="{% url 'subscription:registerPremium' %}" method="post" id="payment-form">
                                        {% csrf_token %}
                                        <div class="form-row row label-heading">
                                                <label for="card-element">
                                                        Credit or debit card details
                                                </label>
                                        </div>
                                        <div class="row card-details">
                                                <div id="card-element">
                                                        <!-- A Stripe Element will be inserted here. -->
                                                </div>

                                                <!-- Used to display form errors. -->
                                                <div id="card-errors" role="alert"></div>
                                        </div>
                                        <div class="row button-submit">
                                                <button type="submit" class="btn btn-primary">Pay</button>
                                        </div>
                                </form>
                        </div>
                </div>
        </div>
</div>


<link rel="stylesheet" href="{% static 'css/checkout1.css' %}">
<script src="{% static 'js/checkout.js' %}"></script>
{% endblock %}